version: "3.9"

services:
  db:
    image: postgres:13
    container_name: db
    restart: always
    env_file:
      - .env
    ports:
      - 5432
    environment:
      - "POSTGRES_PASSWORD:${POSTGRES_PASSWORD}"
      - "POSTGRES_DB:${POSTGRES_DB}"
      - "POSTGRES_USER:${POSTGRES_USER}"
    volumes:
      - data_db:/var/lib/postgresql/data
volumes:
  data_db:


#   db:
#     image: postgres:13
#     container_name: db-pics-manager
#     ports:
#       - "5432"
#     volumes:
#       - postgres-volume:/var/lib/postgresql/data
#     environment:
#       POSTGRES_DB: db
#       POSTGRES_USER: pics-manager
#       POSTGRES_PASSWORD_FILE: /run/secrets/db_password
#     networks:
#       - backend
#     secrets:
#       - db_password

# volumes:
#   postgres-volume:

# networks:
#   default:
#   backend:

# secrets:
#   db_password:
#     file: db_password.txt