spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driverClassName: org.postgresql.Driver
  cors:
    origins:
      - *
      # - http://localhost:2222
      # - http://localhost:45981
      # - http://192.168.232.2:*
      # - http://192.168.232.2:35338
      # - http://localhost:46449
      # - http://192.168.43.1:39760

