# Stage 1: Build the application
FROM maven:3.8.5-openjdk-17 AS build

# Set the working directory
WORKDIR /app

# Copy the pom.xml and install dependencies (this will cache the dependencies layer)
COPY pom.xml .
COPY src ./src
COPY .env .env

RUN mvn clean package -DskipTests

# Stage 2: Run the application
FROM openjdk:24

# Set the working directory
WORKDIR /app

# Copy the jar from the build stage
COPY --from=build /app/target/back-0.0.1-SNAPSHOT.jar /app/back.jar

# Expose the application port
EXPOSE 8080

# Command to run the application
ENTRYPOINT ["java", "-jar", "/app/back.jar"]